#!/usr/bin/env python3
"""
Generative Drawing Agent
Creates a stand-alone turtle script from a free-form prompt.
"""
import datetime
import textwrap
import turtle  # only used to get the colour list for validation

PROMPT = "Prompt ▸ "

# ---------- internal helpers -------------------------------------------------
def _valid_colour(c: str) -> bool:
    return c.lower() in {x.lower() for x in turtle.colormode().colornames}

def _sanitize_name(name: str) -> str:
    return "".join(x if x.isalnum() or x in "_-" else "_" for x in name)

# ---------- prompt → code ----------------------------------------------------
def prompt_to_code(prompt: str) -> str:
    """
    Very small rule-based compiler.
    You can swap this out for an LLM call if you have one.
    """
    # crude keyword spotting
    lc = prompt.lower()
    primitives = []

    # --- background ---------------------------------------------------------
    bg = "white"
    if "black" in lc or "night" in lc:
        bg = "black"
    if "blue" in lc and "sky" in lc:
        bg = "skyblue"
    primitives.append(f"screen.bgcolor('{bg}')")

    # --- sun -----------------------------------------------------------------
    if "sun" in lc:
        col = "yellow" if bg != "yellow" else "orange"
        primitives.append(f"""\
# sun
turtle.penup()
turtle.goto(-150, 150)
turtle.dot(80, '{col}')""")

    # --- house ---------------------------------------------------------------
    if any(x in lc for x in ("house", "home", "building")):
        primitives.append("""\
# house body
turtle.penup()
turtle.goto(-100, -50)
turtle.pendown()
turtle.color('black', 'brown')
turtle.begin_fill()
for _ in range(4):
    turtle.forward(200)
    turtle.left(90)
turtle.end_fill()""")
        # roof
        primitives.append("""\
# roof
turtle.goto(-110, -50)
turtle.color('black', 'red')
turtle.begin_fill()
for a in (60, 60, 60):
    turtle.forward(220)
    turtle.left(180-a)
turtle.end_fill()""")
        # door
        primitives.append("""\
# door
turtle.penup()
turtle.goto(-30, -100)
turtle.pendown()
turtle.color('black', 'darkgreen')
turtle.begin_fill()
for w, h in ((60, 50), (60, 50)):
    turtle.forward(w)
    turtle.left(90)
    turtle.forward(h)
    turtle.left(90)
turtle.end_fill()""")

    # --- heart ---------------------------------------------------------------
    if "heart" in lc:
        col = "red" if "red" in lc else "pink"
        primitives.append(f"""\
# heart
turtle.penup()
turtle.goto(0, -20)
turtle.pendown()
turtle.color('{col}')
turtle.begin_fill()
turtle.left(50)
turtle.forward(60)
turtle.circle(30, 200)
turtle.right(120)
turtle.circle(30, 200)
turtle.forward(60)
turtle.end_fill()""")

    # --- text ----------------------------------------------------------------
    if "write" in lc or "text" in lc or "say" in lc:
        # crude: grab first quoted string
        import re
        m = re.search(r'["“](.*?)["”]', prompt)
        txt = m.group(1) if m else "Hello"
        primitives.append(f"""\
# text
turtle.penup()
turtle.goto(0, -180)
turtle.color('black')
turtle.write('{txt}', align='center', font=('Arial', 24, 'bold'))""")

    # --- footer --------------------------------------------------------------
    code = f"""\
import turtle
screen = turtle.Screen()
screen.title("Generated by Drawing Agent")
{chr(10).join(primitives)}
turtle.hideturtle()
turtle.done()
"""
    return code

# ---------- CLI --------------------------------------------------------------
def main():
    prompt = input(PROMPT).strip()
    if not prompt:
        print("Empty prompt – nothing to draw.")
        return
    code = prompt_to_code(prompt)
    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    fname = f"draw_{stamp}.py"
    with open(fname, "w", encoding="utf8") as f:
        f.write(code)
    print(f"Generated → {fname}")
    print("Run the file to see the picture.")

if __name__ == "__main__":
    main()